#!/usr/bin/env bash
# Script to transfer a file to a remote server using scp

# Check if exactly 4 arguments are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables for clarity
FILE="$1"
IP="$2"
USER="$3"
KEY="$4"

# Use scp to copy the file to the user's home directory on the remote server
scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "$USER@$IP:~/"

