#!/usr/bin/env bash
# This script transfers a file from the client to a remote server using SCP

# Check if exactly 4 arguments are passed
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Transfer file to remote user's home directory using scp
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$IP:~/"

