#!/usr/bin/env bash
# Installs and configures Nginx to return Holberton School 

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y
sudo apt-get install -y ufw

echo -e "\nSetting up some minor stuff.\n"

sudo ufw enable;

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.html /var/www/html/index.html.bckp

# Creating new index
echo -e "!Holberton School for the win" | dd status=none of=/var/www/html/index.html

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted. \n"
